### ISSUE TITLE
inertial offset is wrong 

### ISSUE THREAD

**Issue by nag92** [WPI-AIM/ambf_addon#1]
There is a problem when CoM is calculated. It is not transforming it into the local frame correctly. It is putting the center of mass way outside the geometry. The attached blender file the issue. 

[two_legs.blend.zip](https://github.com/adnanmunawar/blender_afmb_addon/files/2775188/two_legs.blend.zip)

**Comment by nag92** [comment]
It seems to be off by a factor of 10.

**Comment by adnanmunawar** [comment]
Good catch, thank for reporting this. Based on your blend file, you're mixing units from mm to cm to some in meters. Blender reports the meshes vertices whichever way you set them without the underlying unit information. We are using those mesh vertices to calculate the COM (assuming to in meters since Blender by default is unit-less). Can you double check with converting all your units to meters meanwhile I shall see what is the best way to address mismatched units.

**Comment by adnanmunawar** [comment]
Please check out the new commit and see if it works as expected. I also found out that scaling a mesh does not change the reported vertices so I fixed that as well. You should be able to use any units now.

**Comment by nag92** [comment]
It looks like that fixed the issue
